export default [
  {id: '1', value: 'Hanna', image: require('../../assets/images/users/hanna.jpg'), code:'1111'},
  {id: '2', value: 'Eddy', image: require('../../assets/images/users/eddy.jpg'), code:'0000'},
  {id: '3', value: 'Johan S', image: require('../../assets/images/users/johans.jpg'), code:'0000'},
  {id: '4', value: 'Marianne', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '5', value: 'Catharina', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '6', value: 'Henry', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '7', value: 'Lina', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '8', value: 'Angela', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '9', value: 'Orhan', image: require('../../assets/images/users/orhan.jpg'), code:'0000'},
  {id: '10', value: 'Kristoffer', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '11', value: 'Johan G', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '12', value: 'Alexis', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '13', value: 'Janne', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '14', value: 'Sebbe', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
  {id: '15', value: 'Micke', image: require('../../assets/images/users/micke.jpg'), code:'0000'},
  {id: '16', value: 'Rikard', image: require('../../assets/images/users/hanna.jpg'), code:'0000'},
];
